// ─── Sunrise Koan Library ─────────────────────────────────────────────────────
// Zen koans and contemplative questions — one per day, rotated by day-of-year.

const KOANS = [
  "What is the sound of one hand?",
  "What was your face before your parents were born?",
  "Does a dog have Buddha-nature?",
  "Who is dragging this body of yours around?",
  "Before thinking — who are you?",
  "The ten thousand things return to the one. Where does the one return to?",
  "How do you take a step forward from the top of a hundred-foot pole?",
  "What is your original home?",
  "If everything is one, what is one?",
  "When you can do nothing, what can you do?",
  "Who hears?",
  "Without using words, how do you express the truth?",
  "What remains when all thoughts are gone?",
  "What is it that is aware of this moment?",
  "Why did Bodhidharma come from the west?",
  "Is it the flag that moves, or the wind?",
  "What is the colour of wind?",
  "Where does the path lead when there is no road?",
  "What was before the beginning?",
  "Can you take a step without moving?",
  "If all things arise and pass away, what are you?",
  "Can you hear the silence between two thoughts?",
  "If you let go of everything, what is left?",
  "Before sunrise, who greets the dawn?",
  "What is the shape of emptiness?",
  "Who is the one who is seeking?",
  "What is the silence beneath all sound?",
  "What does the river know that the mountain does not?",
  "If the mind is a mirror, who is reflected?",
  "When the bell rings and its sound fades — where does the sound go?",
  "What is so obvious you have never seen it?",
  "Can you catch the shadow of a bird in flight?",
  "What would remain of you if you subtracted all your stories?",
  "The gate is open. Why do you still stand outside?",
  "What is behind your eyes?",
  "In this very moment, are you free?",
  "What are you before you become anything?",
  "Who witnesses the witness?",
  "If everything changes, what does not?",
  "What is neither light nor dark, neither thought nor silence?",
  "What is the work that cannot be finished?",
  "What would you be if you were not afraid?",
  "What is this?",
  "Where do you go when you are not anywhere?",
  "Where are you right now — truly?",
  "What is it you carry that cannot be put down?",
  "If this moment is all there is, what are you waiting for?",
  "What is your true nature beneath all you have been told you are?",
  "What happens to a flame when the candle is blown out?",
  "A monk asked: 'What is the Buddha?' The master replied: 'Three pounds of flax.' What does this mean?",
  "Is the cup empty, or full?",
  "What is the sound of this very moment?",
  "What is the question you are afraid to ask yourself?",
  "Before you were born, who were you?",
  "Where does the path go after it disappears?",
  "What is the weight of a thought?",
  "Can still water have waves?",
  "Who is at home?",
  "What are you not looking at right now?",
  "Where does yesterday live?",
  "What is the sound of one life?",
  "If the self is a river, who is drowning?",
  "What is the distance between you and this moment?",
  "What do you return to when there is nowhere left to go?",
];
