// ─── Sunrise Daily Questions ──────────────────────────────────────────────────
// 60 thought-provoking questions — for reflection, feeling, and growth.
// Rotates by day-of-year. Custom questions (from localStorage) are appended
// to the pool, so they enter the rotation too.

const DAILY_QUESTIONS = [
  "What emotion have you been carrying quietly today?",
  "What would you do today if you weren't afraid?",
  "What does your body need right now that you've been ignoring?",
  "Who have you been meaning to reach out to, and what's held you back?",
  "What belief about yourself are you ready to let go of?",
  "If your future self could send you one message today, what would it say?",
  "What part of your life feels out of alignment with who you want to be?",
  "What are you pretending not to know?",
  "When did you last feel truly at peace, and what was happening?",
  "What small act of courage could you take before the day ends?",
  "What would you do differently if no one was watching?",
  "What are you grieving, even quietly?",
  "What has been draining your energy that you haven't acknowledged?",
  "What does the most honest version of you need to say today?",
  "What are you waiting for permission to do?",
  "What's one thing you've been putting off that, if done, would make everything else easier?",
  "What does rest mean to you right now — and are you getting it?",
  "Where in your life are you being too hard on yourself?",
  "What would you change about yesterday if you could?",
  "What's a feeling you've been labelling as 'fine' that actually isn't?",
  "What kind of person do you want to be remembered as?",
  "What are you most afraid to want?",
  "What part of yourself have you been hiding from others?",
  "What does 'enough' look like for you today?",
  "Where are you spending energy on something that no longer serves you?",
  "What would you tell your younger self about this season of your life?",
  "What does love look like in your life right now?",
  "What's one thing you deeply value that you haven't been honouring?",
  "What habit or thought pattern is quietly holding you back?",
  "When did you last do something just for the joy of it?",
  "What would you attempt if you knew you couldn't fail?",
  "Who in your life makes you feel most like yourself, and why?",
  "What are you ready to forgive — in yourself or someone else?",
  "What boundary have you been afraid to set?",
  "What does success mean to you right now, in this chapter of your life?",
  "What are you secretly proud of that you haven't celebrated?",
  "What are you holding onto that would feel better to release?",
  "What does your ideal ordinary day look like?",
  "What truth are you avoiding because it would require change?",
  "What are you doing out of obligation that you could do out of love instead?",
  "What conversation have you been postponing, and what's the cost of waiting?",
  "What does your intuition keep trying to tell you?",
  "What in your life is asking for more of your attention?",
  "What would it mean to truly accept yourself as you are right now?",
  "What are you comparing yourself to that isn't fair to who you are?",
  "What's one thing that always lifts your spirit, and have you made space for it lately?",
  "What would you do with this day if you treated it as a gift?",
  "What's been sitting on your heart that you haven't yet put into words?",
  "Where are you playing small when you could show up bigger?",
  "What does courage feel like in your body — and where do you feel it today?",
  "What would change in your life if you believed you were worthy of good things?",
  "What relationship in your life most needs your presence and care right now?",
  "What would you stop doing immediately if you trusted yourself more?",
  "Where have you been seeking approval that you could give yourself instead?",
  "What does your heart want that your head keeps talking you out of?",
  "What's one thing you're grateful for that you rarely acknowledge?",
  "What are you creating, building, or growing — even in small ways?",
  "What does showing up for yourself look like today?",
  "What would make today feel meaningful, even in a small way?",
  "What's one word that describes how you want to feel by the end of today?",
];
