// ─── Sunrise Quote Library ────────────────────────────────────────────────────
// 60+ curated quotes — insightful, inspiring, thought-provoking.
// Rotates by day-of-year so each day gets a consistent, different quote.

const QUOTES = [
  { text: "The present moment is the only time over which we have dominion.", author: "Thich Nhat Hanh" },
  { text: "Wherever you are, be all there.", author: "Jim Elliot" },
  { text: "The quality of your life is the quality of your relationships.", author: "Anthony Robbins" },
  { text: "Do not go where the path may lead; go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "The most difficult thing is the decision to act. The rest is merely tenacity.", author: "Amelia Earhart" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
  { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
  { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Tell me, what is it you plan to do with your one wild and precious life?", author: "Mary Oliver" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "To the mind that is still, the whole universe surrenders.", author: "Lao Tzu" },
  { text: "Not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
  { text: "You are enough. You have always been enough.", author: "" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
  { text: "Joy is not in things; it is in us.", author: "Richard Wagner" },
  { text: "The privilege of a lifetime is to become who you truly are.", author: "Carl Jung" },
  { text: "Be kind, for everyone you meet is fighting a harder battle.", author: "Plato" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "To live is the rarest thing in the world. Most people just exist.", author: "Oscar Wilde" },
  { text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Darkness cannot drive out darkness; only light can do that.", author: "Martin Luther King Jr." },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "The wound is the place where the light enters you.", author: "Rumi" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { text: "Everything is figureoutable.", author: "Marie Forleo" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "A ship in harbour is safe, but that's not what ships are for.", author: "John A. Shedd" },
  { text: "The most courageous act is still to think for yourself. Aloud.", author: "Coco Chanel" },
  { text: "Gratitude turns what we have into enough.", author: "" },
  { text: "The present moment always will have been.", author: "" },
  { text: "You cannot step into the same river twice.", author: "Heraclitus" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "We are shaped by our thoughts; we become what we think.", author: "Buddha" },
  { text: "One day or day one. You decide.", author: "" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Nothing in life is to be feared, only to be understood. Now is the time to understand more, so that we may fear less.", author: "Marie Curie" },
  { text: "Your life is your message to the world. Make sure it's inspiring.", author: "Lorrin L. Lee" },
  { text: "Small acts, when multiplied by millions of people, can transform the world.", author: "Howard Zinn" },
  { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "The only limits are, as always, those of vision.", author: "James Broughton" },
  { text: "Be patient with yourself. Self-growth is tender; it's holy ground. There is no greater investment.", author: "Stephen Covey" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "Rest if you must, but don't you quit.", author: "Edgar A. Guest" },
];
